server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3307/uniclub
    username: root
    password: se184190
  jpa:
    hibernate:
      ddl-auto: none

jwt:
  secret: SaP7ZI/7gtXgHkeRldpNLzF+OJnqwBGjPTLHEumC8ew=